---
title: "Schedule"
---

## Arrival

Participants staying in Warwick University accommodation can check in from 15:00 on the day of arrival (it is not possible to arrange early check-in). Luggage storage is available.

Unless informed otherwise, participants have been booked into [Bluebell](https://warwick.ac.uk/services/conferences/spaces/central-campus-venues/accommodation/bluebell) central campus accommodation, with breakfast provided at [Rootes restaurant](https://campus.warwick.ac.uk//search/623c88c9421e6f5928c0dcae). Check-in for Bluebell is at Central Campus Venues reception, [Senate House](https://campus.warwick.ac.uk//search/623c885f421e6f5928c0c7e3).

Participants arriving at Birmingham airport are recommended to take the free Air-Rail Link monorail to Birmingham International train station, then catch a train to Coventry train station (single ticket £3.10, pay by cash/card at the ticket office/machine). If you have exact change or a contactless payment card (or Apply Pay/Google Pay/etc) you can catch a bus from Coventry train station to Warwick University Interchange (main bus terminal on campus) for £2 single, then it is a few minutes walk to Senate House. Alternatively you can get a taxi/Uber/Bolt from Coventry rail station to Senate House for £10-£15. A taxi all the way from the airport will be around £30. Receipts are required to claim travel expenses from your travel budget (where applicable).

Note there will be very little open on campus on Monday 28 August as it is a holiday, however the [Warwick Arts Centre](https://campus.warwick.ac.uk//search/623c885e421e6f5928c0c7cd) building should be open all day (comfy, quiet places to sit) with [Benugo Bar and Kitchen](https://warwick.ac.uk/services/retail/openingtimes/) open from mid-day. If arriving at the airport very early, it may be best to while away some time there before travelling on (or get some food and drink to bring on to campus). For other days, the on-campus cafes and the grocery store will be open as per the [vacation opening times](https://warwick.ac.uk/services/retail/openingtimes/).

[Delegate Joining Instructions - Central Campus Venues Summer 2023 (Word)](/downloads/Delegate%20Joining%20Instructions%20-%20Central%20Campus%20Venues%20Summer%202023.docx)\
[Frequently Asked Questions - Central Campus Venues Summer 2023 (Word)](/downloads/Frequently%20Asked%20Questions%20-%20Central%20Campus%20Venues%20Summer%202023.docx)

## Email

Eduroam is available, participants should check their home institution for connection instructions, though Warwick IT Services link to some [tools for automated setup](https://warwick.ac.uk/services/its/servicessupport/networkservices/wifi/eduroam/) on computers/mobile devices.

Participants without access to eduroam may use [Warwick Guest WiFi](https://warwick.ac.uk/services/its/servicessupport/networkservices/wifi/warwick-guest/) (mobile phone required to register). Accounts are valid for 7 days on up to 3 devices.

## Registration

The registration desk will be open from 15:00 - 19:30 Tuesday 29 August in the [Faculty of Arts Building (FAB) atrium](https://campus.warwick.ac.uk//search/623c8960421e6f5928c0fb65). The atrium will provide a place to meet other participants as they arrive and will be a good place to hang out before dinner if you arrive early.

If you are staying in university accommodation it is not necessary to register before dinner as you can show your room key to gain entry to the restaurant. Instead you can pick up your name badge on the way to the welcome session.

If you arrive late, you will be able to pick up your name badge at any session in [FAB 5.01](https://campus.warwick.ac.uk//search/623c896c421e6f5928c0fdcd).

## Programme

All whole group sessions in [FAB 5.01](https://campus.warwick.ac.uk//search/623c896c421e6f5928c0fdcd) will be hybrid, with invites sent directly to remote participants.

::: panel-tabset
### Tue 29 Aug

| Time (BST)    | Event                                                                    | Venue                                                                              |
|---------------|---------------------------|-------------------------------|
| 18:00 - 19:00 | Self-service dinner                                                      | [Rootes restaurant](https://campus.warwick.ac.uk//search/623c88c9421e6f5928c0dcae) |
| 19:30 - 20:00 | Welcome session                                                          | [FAB 5.01](https://campus.warwick.ac.uk//search/623c896c421e6f5928c0fdcd)          |
| 20:00 - 22:00 | Social (drinks + nibbles) <br> *sponsored by [Posit](https://posit.co/)* | [FAB Atrium](https://campus.warwick.ac.uk//search/623c8960421e6f5928c0fb65)        |

### Wed 30 Aug

| Time (BST)    | Event                                                                                 | Venue                                                                                        |
|--------------|----------------------------|------------------------------|
| 08:30 - 09:00 | Coffee                                                                                | [FAB 5.01](https://campus.warwick.ac.uk//search/623c896c421e6f5928c0fdcd)                    |
| 09:00 - 10:30 | Kick-off day 1                                                                        | [FAB 5.02/5.03](https://campus.warwick.ac.uk//search/623c896c421e6f5928c0fdce)               |
| 10:30 - 11:00 | Coffee                                                                                | [FAB 5.01](https://campus.warwick.ac.uk//search/623c896c421e6f5928c0fdcd)                    |
| 11:00 - 12:30 | Small groups                                                                          | Various, FAB                                                                                 |
| 12:30 - 13:30 | Lunch                                                                                 | [Rootes restaurant](https://campus.warwick.ac.uk//search/623c88c9421e6f5928c0dcae)           |
| 13:30 - 15:00 | Small groups                                                                          | Various, FAB                                                                                 |
| 15:00 - 15:30 | Coffee                                                                                | [FAB 5.01](https://campus.warwick.ac.uk//search/623c896c421e6f5928c0fdcd)                    |
| 15:30 - 17:00 | Small groups                                                                          | Various, FAB                                                                                 |
| 17:00 - 17:30 | Report back (part 1)                                                                  | [FAB 5.02/5.03](https://campus.warwick.ac.uk//search/623c896c421e6f5928c0fdce)               |
| 19:00 - 21:00 | Sit-down dinner <br> *sponsored by [The R Consortium](https://www.r-consortium.org/)* | [Radcliffe Conference Centre](https://campus.warwick.ac.uk//search/623c88a9421e6f5928c0d61e) |

### Thu 31 Aug

| Time (BST)    | Event                                                                                      | Venue                                                                                                |
|--------------|---------------------------|-------------------------------|
| 08:30 - 09:00 | Coffee                                                                                     | [FAB 5.01](https://campus.warwick.ac.uk//search/623c896c421e6f5928c0fdcd)                            |
| 09:00 - 09:30 | Report back (part 2)                                                                       | [FAB 5.02/5.03](https://campus.warwick.ac.uk//search/623c896c421e6f5928c0fdce)                       |
| 09:30 - 10:00 | Kick-off day 2                                                                             | [FAB 5.02/5.03](https://campus.warwick.ac.uk//search/623c896c421e6f5928c0fdce)                       |
| 10:00 - 10:30 | Coffee                                                                                     | [FAB 5.01](https://campus.warwick.ac.uk//search/623c896c421e6f5928c0fdcd)                            |
| 10:30 - 12:30 | Small groups                                                                               | Various, FAB                                                                                         |
| 12:30 - 13:30 | Lunch                                                                                      | [Rootes restaurant](https://campus.warwick.ac.uk//search/623c88c9421e6f5928c0dcae)                   |
| 13:30 - 15:00 | Small groups                                                                               | Various, FAB                                                                                         |
| 15:00 - 15:30 | Coffee                                                                                     | [FAB 5.01](https://campus.warwick.ac.uk//search/623c896c421e6f5928c0fdcd)                            |
| 15:30 - 16:30 | Small groups                                                                               | Various, FAB                                                                                         |
| 17:00 - 18:00 | Warwick RUG (report back)                                                                  | [MS.01](https://campus.warwick.ac.uk//search/623c88f9421e6f5928c0e669), Zeeman Building              |
| 18:00 - 19:00 | Refreshments                                                                               | Outside [MS.01](https://campus.warwick.ac.uk//search/623c88f9421e6f5928c0e669), Zeeman Building      |
| 19:00 - 21:00 | Buffet dinner <br> *sponsored by [CRiSM](https://warwick.ac.uk/fac/sci/statistics/crism/)* | [Chancellor's Suite](https://campus.warwick.ac.uk//search/623c88ca421e6f5928c0dce4), Rootes Building |

### Fri 1 Sep

| Time (BST)    | Event             | Venue                                                                              |
|--------------|--------------|---------------------------------------------|
| 08:30 - 09:00 | Coffee            | [FAB 5.01](https://campus.warwick.ac.uk//search/623c896c421e6f5928c0fdcd)          |
| 09:00 - 09:30 | Report back (ctd) | [FAB 5.02/5.03](https://campus.warwick.ac.uk//search/623c896c421e6f5928c0fdce)     |
| 09:30 - 10:00 | Kick-off day 3    | [FAB 5.02/5.03](https://campus.warwick.ac.uk//search/623c896c421e6f5928c0fdce)     |
| 10:00 - 10:30 | Coffee            | [FAB 5.01](https://campus.warwick.ac.uk//search/623c896c421e6f5928c0fdcd)          |
| 10:30 - 12:30 | Small groups      | Various, FAB                                                                       |
| 12:30 - 13:30 | Lunch             | [Rootes restaurant](https://campus.warwick.ac.uk//search/623c88c9421e6f5928c0dcae) |
| 13:30 - 15:00 | Wrap-up           | [FAB 5.02/5.03](https://campus.warwick.ac.uk//search/623c896c421e6f5928c0fdce)     |
| 15:00 - 15:30 | Coffee            | [FAB 5.01](https://campus.warwick.ac.uk//search/623c896c421e6f5928c0fdcd)          |
:::

## Venues

Key venues of the sprint:

-   [Senate House](https://campus.warwick.ac.uk//search/623c885f421e6f5928c0c7e3) - Central Campus Venues Reception
-   [Bluebell residences](https://campus.warwick.ac.uk//search/623c8860421e6f5928c0c829) - main accommodation
-   [Faculty of Arts Building (FAB)](https://campus.warwick.ac.uk//search/623c8866421e6f5928c0c937) - main sprint venue
-   [Rootes Building](https://campus.warwick.ac.uk//search/623c8855421e6f5928c0c779) - main venue for meals
-   [Radcliffe conference centre](https://campus.warwick.ac.uk//search/623c8859421e6f5928c0c79c) - venue for sit-down dinner
-   [Zeeman Building](https://campus.warwick.ac.uk//search/623c8859421e6f5928c0c79c) - venue for Warwick R User Group meeting

Links above go to the [interactive campus map](https://warwick.ac.uk/about/visiting/maps/interactive). The main venues are also highlighted on this [PDF campus map](/downloads/Conference%20map%20-%20annotated.pdf).

## Breakout space

We have use of the following breakout spaces in FAB during the sprint, in addition to the main room (FAB 5.01). The first number is the floor the space is on.

| Room                                                                                              | Capacity | Type      | Layout    | Facilities  |
|---------------------------------------------------------------------------------------------------|----------|-----------|-----------|-------------|
| [2.25](https://warwick.ac.uk/services/its/servicessupport/av/lecturerooms/roominformation/fab225) | 38       | Open      | Cabaret   |             |
| [2.43](https://warwick.ac.uk/services/its/servicessupport/av/lecturerooms/roominformation/fab243) | 50       | Closed    | Cabaret   | 2 x webcam  |
| [2.47](https://warwick.ac.uk/services/its/servicessupport/av/lecturerooms/roominformation/fab247) | 13       | Open      | Boardroom |             |
| [2.48](https://warwick.ac.uk/services/its/servicessupport/av/lecturerooms/roominformation/fab248) | 13       | Closed    | Boardroom | webcam      |
| [2.61](https://warwick.ac.uk/services/its/servicessupport/av/lecturerooms/roominformation/fab261)                                                                                       | 16       | Open      | Boardroom |             |
| [3.26](https://warwick.ac.uk/services/its/servicessupport/av/lecturerooms/roominformation/fab326) | 20       | Semi-open | Cabaret   |             |
| [4.52](https://warwick.ac.uk/services/its/servicessupport/av/lecturerooms/roominformation/fab452) | 20       | Semi-open | Cabaret   |             |
| [4.74](https://warwick.ac.uk/services/its/servicessupport/av/lecturerooms/roominformation/fab474) | 20       | Semi-open | Cabaret   |             |
| [6.03](https://warwick.ac.uk/services/its/servicessupport/av/lecturerooms/roominformation/fab603) | 13       | Closed    | Boardroom | quiet space |
